#include "pch.h"
#include "TidalSchema.h"
using namespace LocalDB;
using namespace LocalDB::SchemaDefinition;
void localdata::TidalSchema::BuildSchema(SchemaBuilder & builder)
{
	builder
		.table("playback_reports", 11)
			.column("id", SqliteType::Int64)
				.isPrimaryKey(true)
				.nullable(false)
			.endColumn()
			.column("json", SqliteType::Text)
				.nullable(false)
			.endColumn()
		.endTable()
		.table("cached_track")
			.column("id", SqliteType::Int64)
				.isPrimaryKey(true)
				.nullable(false)
			.endColumn()
			.column("quality", SqliteType::Int64)
				.nullable(false)
			.endColumn()
			.column("server_timestamp", SqliteType::Int64)
				.nullable(false)
			.endColumn()
			.column("server_size", SqliteType::Int64)
				.nullable(false)
			.endColumn()		
			.column("local_size", SqliteType::Int64)
				.nullable(false)
			.endColumn()
			.column("last_playpack_time", SqliteType::Int64, 2)
				.nullable(false)
				.defaultValue("0")
			.endColumn()
			.column("obuscated", SqliteType::Int64, 10)
				.nullable(false)
				.defaultValue("0")
			.endColumn()
		.endTable()
		.table("imported_track", 3)
			.column("id", SqliteType::Int64)
				.isPrimaryKey(true)
				.nullable(false)
			.endColumn()
		
			.column("quality", SqliteType::Int64)
				.nullable(false)
			.endColumn()
			
			.column("last_playpack_time", SqliteType::Int64)
				.nullable(false)
				.defaultValue("0")
			.endColumn()
			.column("album_id", SqliteType::Int64)
				.nullable(false)
			.endColumn()
			.column("album_title", SqliteType::Text)
				.nullable(false)
			.endColumn()	
			.column("cover", SqliteType::Text)
				.nullable(false)
			.endColumn()
			.column("title", SqliteType::Text)
				.nullable(false)
			.endColumn()
			.column("artist", SqliteType::Text)
				.nullable(false)
			.endColumn()
			.column("json", SqliteType::Text)
				.nullable(false)
			.endColumn()
			.column("import_timestamp", SqliteType::Int64, 4)
				.nullable(false)
		.defaultValue("0")
			.endColumn()
			.column("size", SqliteType::Int64, 9)
				.nullable(false)
				.defaultValue("0")
			.endColumn()
		.column("obuscated", SqliteType::Int64, 10)
		.nullable(false)
		.defaultValue("0")
		.endColumn()
		.endTable()
		.index("imported_track_natural_sort", "imported_track",8)
			.addColumn("artist")
			.addColumn("album_title")
			.addColumn("title")
		.endIndex()
		.table("imported_album", 3)
			.column("id", SqliteType::Int64)
				.isPrimaryKey(true)
				.nullable(false)
			.endColumn()
			.column("cover", SqliteType::Text)
				.nullable(false)
			.endColumn()
			.column("title", SqliteType::Text)
				.nullable(false)
			.endColumn()
			.column("artist", SqliteType::Text)
				.nullable(false)
			.endColumn()
			.column("json", SqliteType::Text)
				.nullable(false)
			.endColumn()
			.column("tracks_json", SqliteType::Text)
				.nullable(false)
			.endColumn()
			.column("import_timestamp", SqliteType::Int64, 4)
				.nullable(false)
		.defaultValue("0")
			.endColumn()
		.endTable()
		.index("imported_album_by_title","imported_album", 3 )
			.addColumn("title")
		.endIndex()
		.table("imported_playlist", 3)
			.column("id", SqliteType::Text)
				.isPrimaryKey(true)
				.nullable(false)
			.endColumn()
			.column("cover", SqliteType::Text)
				.nullable(false)
			.endColumn()
			.column("title", SqliteType::Text)
				.nullable(false)
			.endColumn()
			.column("json", SqliteType::Text)
				.nullable(false)
			.endColumn()
			.column("tracks_json", SqliteType::Text)
				.nullable(false)
			.endColumn()
			.column("updated_at", SqliteType::Int64)
				.nullable(false)
			.endColumn()
			.column("import_timestamp", SqliteType::Int64, 4)
				.nullable(false)
					.defaultValue("0")
			.endColumn()
		.endTable()
		.index("imported_playlist_by_title", "imported_playlist", 3)
			.addColumn("title")
		.endIndex()
		.table("track_import_job", 3)
			.column("id", SqliteType::Int64)
				.isPrimaryKey(true)
				.nullable(false)
			.endColumn()
			.column("server_timestamp", SqliteType::Int64)
				.nullable(false)
			.endColumn()
			.column("server_size", SqliteType::Int64)
				.nullable(false)
			.endColumn()		
			.column("local_size", SqliteType::Int64)
				.nullable(false)
			.endColumn()
			.column("cover", SqliteType::Text)
				.nullable(false)
			.endColumn()
			.column("title", SqliteType::Text)
				.nullable(false)
			.endColumn()
			.column("artist", SqliteType::Text)
				.nullable(false)
			.endColumn()
			.column("import_timestamp", SqliteType::Int64, 4)
				.nullable(false)
				.defaultValue("0")
			.endColumn()
			.column("owning_albumid", SqliteType::Int64, 5)
				.nullable(false)
				.defaultValue("0")
			.endColumn()
			.column("owning_playlistid", SqliteType::Text, 5)
				.nullable(false)
				.defaultValue("''")
			.endColumn()
			.column("quality", SqliteType::Int64, 6)
				.nullable(false)
				.defaultValue("0")
			.endColumn()
			.column("obuscated", SqliteType::Int64, 10)
			.nullable(false)
			.defaultValue("0")
			.endColumn()
		.endTable()
		.index("track_import_job_by_timestamp", "track_import_job", 7)
			.addColumn("import_timestamp")
		.endIndex();
			
			//auto entities = LocalDB::SchemaDefinition::generateEntitiesClasses(builder.definition(), { "localdata" });
			//OutputDebugStringA(entities.c_str());
}
